version: 2
jobs:
    build:
        docker:
            - image: docker:17.07.0-ce-git
        working_directory: /go/src/github.com/ieee0824/circleci-docker-multi-stage-build
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.05.0-ce
            # baseになるDocker Imageがdocker入ってないときはdocker clientを入れる必要がある
            # 今回の場合は不必要
            #- run:
            #    name: Install Docker client
            #    command: |
            #        VER="17.05.0-ce"
            #        curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            #        tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            #        mv /tmp/docker/* /usr/bin
            - run:
                name: test build
                command: |
                    docker build .
